### ISSUE TITLE
Skygrid caused exception error (null)

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/SkyGrid#26]
#### Describe the bug

```
[12:03:22 INFO]: 1MBNetwork issued server command: /skygrid go
[12:03:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'skygrid go' in world.bentobox.skygrid.commands.SkyGridCommand(skygrid)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at world.bentobox.bentobox.managers.IslandsManager.isSafeLocation(IslandsManager.java:204) ~[?:?]
        at world.bentobox.bentobox.managers.IslandsManager.getSafeHomeLocation(IslandsManager.java:490) ~[?:?]
        at world.bentobox.bentobox.managers.IslandsManager.homeTeleport(IslandsManager.java:620) ~[?:?]
        at world.bentobox.bentobox.managers.IslandsManager.homeTeleport(IslandsManager.java:582) ~[?:?]
        at world.bentobox.skygrid.commands.GoCommand.execute(GoCommand.java:47) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        ... 14 more
>
```

#### Steps to reproduce the behavior

one of the admins wanted to try skygrid and typed: /skygrid create, which gave help (so we assumed we had to just type /skygrid) 

He then typed: /skygrid, which gave this error.

Then he typed: /skygrid go, which created the skygrid island and teleported him. 
He showed up in spectator mode, but as far as we know, he was in creative mode.

#### Expected behavior

didn't expect an error in console

expected /skygrid create, just like /skyblock create

#### Server

 - OS: **macos mojave**
 - Java version: **11**

#### Plugins

```
mv-core, mv-inv, cmi, we/wg, bentobox
```

##### BentoBox and Addons

```
>bentobox version
[12:07:50 INFO]: Running SPIGOT 1.13.2.
[12:07:50 INFO]: BentoBox version: 1.7.0-SNAPSHOT-b1342
[12:07:50 INFO]: Database: JSON
[12:07:50 INFO]: Loaded Game Worlds:
[12:07:50 INFO]: acid (acid): Overworld, Nether, End
[12:07:50 INFO]: cave (cave): Overworld, Nether, End
[12:07:50 INFO]: skyblock (skyblock): Overworld, Nether, End
[12:07:50 INFO]: skygrid (skygrid): Overworld, Nether, End
[12:07:50 INFO]: Loaded Addons:
[12:07:50 INFO]: AcidIsland 1.6.0-SNAPSHOT-b432 (ENABLED)
[12:07:50 INFO]: BSkyBlock 1.6.0 (ENABLED)
[12:07:50 INFO]: CaveBlock 1.6.0 (ENABLED)
[12:07:50 INFO]: Greenhouses 0.3.2-SNAPSHOT (ENABLED)
[12:07:50 INFO]: Level 1.7.0-SNAPSHOT-b282 (ENABLED)
[12:07:50 INFO]: Limits 1.6.0 (ENABLED)
[12:07:50 INFO]: MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
[12:07:50 INFO]: SkyGrid 1.7.0-SNAPSHOT (ENABLED)
[12:07:50 INFO]: WelcomeWarps 1.6.2-SNAPSHOT-b176 (ENABLED)
>

>ver
[12:07:56 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[12:07:56 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
>
```

##### Configuration

 - Database: **flatfile**

**Comment by tastybento** [comment]
- `/skygrid` is the correct command to start your SkyGrid adventure
- There is no create command in SkyGrid because there are no "islands"
- The reported error was occurring for players who typed `/skygrid go` without having done `/skygrid` before. That's now fixed.
