### ISSUE TITLE
startup error due to GRASS in config file

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/SkyGrid#65]
### Expected behavior

smooth startup..

### Observed/Actual behavior

red warning, and addon fails to load.

### Steps/models to reproduce

skygrid/config.yml

keep it GRASS

### BentoBox version

```
> bbox version
[14:53:20 INFO]: Running PAPER 1.20.4.
[14:53:20 INFO]: BentoBox version: 2.0.0-SNAPSHOT-b2514
[14:53:20 INFO]: Database: JSON
[14:53:20 INFO]: Loaded Game Worlds:
[14:53:20 INFO]: acid (acid): Overworld
[14:53:20 INFO]: cave (cave): Overworld
[14:53:20 INFO]: oneblock (oneblock): Overworld
[14:53:20 INFO]: parkour (parkour): Overworld
[14:53:20 INFO]: skyblock (skyblock): Overworld
[14:53:20 INFO]: skygrid (skygrid): Overworld
[14:53:20 INFO]: Loaded Addons:
[14:53:20 INFO]: AcidIsland 1.18.1-SNAPSHOT-b1008 (ENABLED)
[14:53:20 INFO]: AOneBlock 1.15.0-SNAPSHOT-b384 (ENABLED)
[14:53:20 INFO]: Biomes 2.2.0-SNAPSHOT-b255 (ENABLED)
[14:53:20 INFO]: Border 4.1.1-SNAPSHOT-b187 (ENABLED)
[14:53:20 INFO]: BSkyBlock 1.17.0-SNAPSHOT-b751 (ENABLED)
[14:53:20 INFO]: CauldronWitchery 2.1.0-SNAPSHOT-#58 (ENABLED)
[14:53:20 INFO]: CaveBlock 1.19.0-SNAPSHOT-b444 (ENABLED)
[14:53:20 INFO]: Challenges 1.3.0-SNAPSHOT-b538 (ENABLED)
[14:53:20 INFO]: FarmersDance 1.0.0-SNAPSHOT (ENABLED)
[14:53:20 INFO]: Greenhouses 1.7.4-SNAPSHOT-b364 (ENABLED)
[14:53:20 INFO]: Level 2.12.0-SNAPSHOT-b553 (ENABLED)
[14:53:20 INFO]: Limits 1.20.0-SNAPSHOT-b321 (ENABLED)
[14:53:20 INFO]: MagicCobblestoneGenerator 2.6.0-SNAPSHOT-b270 (ENABLED)
[14:53:20 INFO]: Parkour 1.3.1-SNAPSHOT-b86 (ENABLED)
[14:53:20 INFO]: SkyGrid 1.20.0-SNAPSHOT-b419 (ENABLED)
[14:53:20 INFO]: TopBlock 1.0.1-SNAPSHOT-b24 (ENABLED)
[14:53:20 INFO]: Warps 1.14.0-SNAPSHOT-b358 (ENABLED)
>
```

### Plugin list

n/a

### Other

error:
The above issues are gone, but, after another fresh copy of the live server, and using `SkyGrid-1.20.0-SNAPSHOT-b419.jar`, i get this as soon as the server starts.
```
[14:42:20 INFO]: [BentoBox-Warps] Loading server plugin BentoBox-Warps v1.14.0-SNAPSHOT-b358
[14:42:20 INFO]: [BentoBox-FarmersDance] Loading server plugin BentoBox-FarmersDance v1.0.0-SNAPSHOT-b9
[14:42:20 INFO]: [BentoBox-SkyGrid] Loading server plugin BentoBox-SkyGrid v1.20.0-SNAPSHOT-b419
[14:42:20 ERROR]: [BentoBox] Skipping SkyGrid due to an unhandled exception...
[14:42:20 ERROR]: [BentoBox] java.lang.ClassCastException: class com.google.common.base.Absent cannot be cast to class java.lang.String (com.google.common.base.Absent is in unnamed module of loader java.net.URLClassLoader @27fa135a; java.lang.String is in module java.base of loader 'bootstrap')
    at BentoBox-2.0.0-SNAPSHOT-b2514.jar//world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.serializeMap(YamlDatabaseHandler.java:451)
    at BentoBox-2.0.0-SNAPSHOT-b2514.jar//world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.saveObject(YamlDatabaseHandler.java:405)
    at BentoBox-2.0.0-SNAPSHOT-b2514.jar//world.bentobox.bentobox.api.configuration.Config.saveConfigObject(Config.java:92)
    at SkyGrid-1.20.0-SNAPSHOT-b419.jar//world.bentobox.skygrid.SkyGrid.saveWorldSettings(SkyGrid.java:127)
    at SkyGrid-1.20.0-SNAPSHOT-b419.jar//world.bentobox.skygrid.SkyGrid.loadSettings(SkyGrid.java:50)
    at SkyGrid-1.20.0-SNAPSHOT-b419.jar//world.bentobox.skygrid.SkyGrid.onLoad(SkyGrid.java:39)
    at BentoBox-2.0.0-SNAPSHOT-b2514.jar//world.bentobox.bentobox.managers.AddonsManager.initializeAddon(AddonsManager.java:245)
    at BentoBox-2.0.0-SNAPSHOT-b2514.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:190)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
    at BentoBox-2.0.0-SNAPSHOT-b2514.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:149)
    at BentoBox-2.0.0-SNAPSHOT-b2514.jar//world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:170)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637)
    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548)
    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1132)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
    at java.base/java.lang.Thread.run(Thread.java:1583)

[14:42:20 INFO]: [BentoBox-AOneBlock] Loading server plugin BentoBox-AOneBlock v1.15.0-SNAPSHOT-b384
[14:42:20 INFO]: [BentoBox-BSkyBlock] Loading server plugin BentoBox-BSkyBlock v1.17.0-SNAPSHOT-b751
```
[config.yml.zip](https://github.com/BentoBoxWorld/SkyGrid/files/13804726/config.yml.zip)

**Comment by tastybento** [comment]
Fixed with latest version.
